name: SlimefunWarfare
main: io.github.seggan.slimefunwarfare.SlimefunWarfare
version: ${version}
authors: [Seggan, Jack]
depend:
  - Slimefun
softdepend:
  - SimpleStorage
  - InfinityExpansion
  - DynaTech
  - TownyFlight
api-version: '1.21'
